#!/usr/bin/env python3
"""Generate Point-LIO mapping override YAML from xmacro source files."""

from __future__ import annotations

import argparse
import math
import re
import sys
import tempfile
from pathlib import Path


WARNING = "# AUTOGENERATED FROM XMACRO - DO NOT EDIT MANUALLY"
GRAVITY_GIMBAL = (0.0, 0.0, -9.81)


class InputError(RuntimeError):
    """Raised when an xmacro source is missing or invalid."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Point-LIO mapping overrides from xmacro extrinsic sources."
    )
    parser.add_argument("--real-xmacro", required=True, type=Path)
    parser.add_argument("--imu-macro", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def read_required(path: Path, label: str) -> str:
    if not path.is_file():
        raise InputError(f"missing {label}: {path}")
    return path.read_text(encoding="utf-8")


def parse_pose_numbers(raw: str, label: str) -> list[float]:
    parts = raw.split()
    if len(parts) != 6:
        raise InputError(f"{label} must contain 6 SDF pose values, got {len(parts)}: {raw!r}")

    values: list[float] = []
    for part in parts:
        try:
            value = float(part)
        except ValueError as exc:
            raise InputError(f"{label} contains non-numeric value {part!r}") from exc
        if not math.isfinite(value):
            raise InputError(f"{label} contains non-finite value {part!r}")
        values.append(value)
    return values


def parse_front_lidar_pose(real_xmacro: Path) -> list[float]:
    text = read_required(real_xmacro, "real xmacro")
    matches = re.findall(r'\bfront_lidar_pose\s*=\s*"([^"]+)"', text)
    if len(matches) != 1:
        raise InputError(
            f"expected exactly one front_lidar_pose attribute in {real_xmacro}, found {len(matches)}"
        )
    return parse_pose_numbers(matches[0], "front_lidar_pose")


def parse_imu_pose(imu_macro: Path) -> list[float]:
    text = read_required(imu_macro, "IMU xmacro")
    matches = re.findall(
        r'<pose\b(?=[^>]*\brelative_to\s*=\s*"\$\{lidar_link\}")[^>]*>(.*?)</pose>',
        text,
        flags=re.DOTALL,
    )
    matches = [match.strip() for match in matches]
    if len(matches) != 1:
        raise InputError(
            f"expected exactly one IMU pose relative_to=\"${{lidar_link}}\" in {imu_macro}, found {len(matches)}"
        )
    return parse_pose_numbers(matches[0], "IMU pose")


def matmul(a: list[list[float]], b: list[list[float]]) -> list[list[float]]:
    return [
        [sum(a[row][idx] * b[idx][col] for idx in range(3)) for col in range(3)]
        for row in range(3)
    ]


def rotation_matrix(roll: float, pitch: float, yaw: float) -> list[list[float]]:
    sr, cr = math.sin(roll), math.cos(roll)
    sp, cp = math.sin(pitch), math.cos(pitch)
    sy, cy = math.sin(yaw), math.cos(yaw)

    rx = [
        [1.0, 0.0, 0.0],
        [0.0, cr, -sr],
        [0.0, sr, cr],
    ]
    ry = [
        [cp, 0.0, sp],
        [0.0, 1.0, 0.0],
        [-sp, 0.0, cp],
    ]
    rz = [
        [cy, -sy, 0.0],
        [sy, cy, 0.0],
        [0.0, 0.0, 1.0],
    ]
    return matmul(matmul(rz, ry), rx)


def transpose_times_vector(matrix: list[list[float]], vector: tuple[float, float, float]) -> list[float]:
    return [sum(matrix[row][col] * vector[row] for row in range(3)) for col in range(3)]


def flatten(matrix: list[list[float]]) -> list[float]:
    return [item for row in matrix for item in row]


def fmt(value: float) -> str:
    if abs(value) < 1e-12:
        value = 0.0
    return f"{value:.12g}"


def inline(values: list[float]) -> str:
    return "[" + ", ".join(fmt(value) for value in values) + "]"


def matrix_yaml(values: list[float]) -> str:
    rows = [values[index : index + 3] for index in range(0, 9, 3)]
    return (
        "[" + ", ".join(fmt(value) for value in rows[0]) + ",\n"
        "                    " + ", ".join(fmt(value) for value in rows[1]) + ",\n"
        "                    " + ", ".join(fmt(value) for value in rows[2]) + "]"
    )


def build_yaml(front_lidar_pose: list[float], imu_pose: list[float]) -> str:
    _, _, _, front_roll, front_pitch, front_yaw = front_lidar_pose
    imu_x, imu_y, imu_z, imu_roll, imu_pitch, imu_yaw = imu_pose

    front_rotation = rotation_matrix(front_roll, front_pitch, front_yaw)
    imu_rotation = rotation_matrix(imu_roll, imu_pitch, imu_yaw)
    gravity = transpose_times_vector(front_rotation, GRAVITY_GIMBAL)
    extrinsic_t = [imu_x, imu_y, imu_z]
    extrinsic_r = flatten(imu_rotation)

    return (
        f"{WARNING}\n"
        "# Source xmacro inputs: wheeled_biped_real.sdf.xmacro front_lidar_pose; mid360_imu_tf.sdf.xmacro IMU pose.\n"
        "# Regenerate by rebuilding sentry_dual_mid360; do not hand-edit this artifact.\n"
        "point_lio:\n"
        "  ros__parameters:\n"
        "    mapping:\n"
        f"      gravity: {inline(gravity)}\n"
        f"      gravity_init: {inline(gravity)}\n"
        f"      extrinsic_T: {inline(extrinsic_t)}\n"
        f"      extrinsic_R: {matrix_yaml(extrinsic_r)}\n"
    )


def write_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=str(path.parent),
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as temp:
        temp.write(text)
        temp_path = Path(temp.name)
    temp_path.replace(path)


def main() -> int:
    args = parse_args()
    try:
        front_lidar_pose = parse_front_lidar_pose(args.real_xmacro)
        imu_pose = parse_imu_pose(args.imu_macro)
        write_atomic(args.output, build_yaml(front_lidar_pose, imu_pose))
    except InputError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
